### ISSUE TITLE
Bug: Exercises search by author, copyright holder, collaborator fail to return any results

### ISSUE THREAD

**Issue by Dantemss** [openstax/exercises#248]
**SCENARIO** _Briefly describe the issue._

Exercises search by author, copyright holder, collaborator fail to return any results

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [x] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [x] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**
Search by author/copyright holder/collaborator

----------------
**Environment:**

- **Instance:**
` [x] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
Can't search

----------------
**Images or Screenshots** (_attach below_)

**Comment by Dantemss** [comment]
Other PRs have already been merged.

**Comment by Malar-Natarajan** [comment]
most exercises have copyright holder "Rice University"
collaborator will search for both author and copyright holder

**Comment by BruceP99166** [comment]
Issue moved to [openstax/tutor #81](https://github.com/openstax/tutor/issues/81) via [**ZenHub**](https://www.zenhub.com/)
