### ISSUE TITLE
CSRF error

### ISSUE THREAD

**Issue by jpslav** [openstax/exercises#61]
method=OPTIONS path=/api/exercises format=*/* controller=webview action=index status=500 duration=3.82 view=0.00 db=0.00 params={"q"=>"tag:apbio-ch05-ex021", "path"=>"api/exercises"}

Can't verify CSRF token authenticity

An exception occurred: ActionController::InvalidAuthenticityToken

**Comment by jpslav** [comment]
@Dantemss you said we need CSRF tokens in the layout plus there was an outdated gem we needed to update?

**Comment by Dantemss** [comment]
The issue is actually that OPTIONS wasn't caught by openstax_api, so I had to update it again.
https://github.com/openstax/exercises/pull/63 should solve this.
